const QUOTES = [
  { quote: "The only bad workout is the one that didn't happen.", author: "Unknown" },
  { quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { quote: "Success starts with self-discipline.", author: "Unknown" },
  { quote: "Your body can stand almost anything. It's your mind you have to convince.", author: "Unknown" },
  { quote: "Don't wish for a good body. Work for it.", author: "Unknown" },
  { quote: "It never gets easier. You just get stronger.", author: "Unknown" },
  { quote: "Wake up. Work out. Look hot. Kick ass.", author: "Unknown" },
  { quote: "Fitness is not about being better than someone else. It's about being better than you used to be.", author: "Khloe Kardashian" },
  { quote: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { quote: "Champions aren't made in the gyms. Champions are made from something they have deep inside them — a desire, a dream, a vision.", author: "Muhammad Ali" },
  { quote: "The difference between try and triumph is just a little umph!", author: "Marvin Phillips" },
  { quote: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { quote: "No matter how slow you go, you are still lapping everyone on the couch.", author: "Unknown" },
  { quote: "You have to expect things of yourself before you can do them.", author: "Michael Jordan" },
  { quote: "The pain you feel today will be the strength you feel tomorrow.", author: "Unknown" },
  { quote: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
  { quote: "Work hard in silence. Let your success be the noise.", author: "Frank Ocean" },
  { quote: "Strength does not come from the physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { quote: "The clock is ticking. Are you becoming the person you want to be?", author: "Greg Plitt" },
  { quote: "If it doesn't challenge you, it doesn't change you.", author: "Fred DeVito" },
  { quote: "Once you see results, it becomes an addiction.", author: "Unknown" },
  { quote: "You're only one workout away from a good mood.", author: "Unknown" },
  { quote: "Train insane or remain the same.", author: "Unknown" },
  { quote: "Strive for progress, not perfection.", author: "Unknown" },
  { quote: "What hurts today makes you stronger tomorrow.", author: "Jay Cutler" },
  { quote: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { quote: "The body achieves what the mind believes.", author: "Unknown" },
  { quote: "If you're tired of starting over, stop giving up.", author: "Unknown" },
  { quote: "Sweat is just fat crying.", author: "Unknown" },
  { quote: "Be stronger than your strongest excuse.", author: "Unknown" },
  { quote: "Eat clean. Train dirty.", author: "Unknown" },
  { quote: "Don't count the days — make the days count.", author: "Muhammad Ali" },
  { quote: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
  { quote: "Your present self is a result of your past choices. Your future self depends on the choices you make today.", author: "Unknown" },
  { quote: "Results don't happen overnight. Trust the process.", author: "Unknown" },
  { quote: "A little progress each day adds up to big results.", author: "Satya Nani" },
  { quote: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
  { quote: "Excuses don't burn calories.", author: "Unknown" },
  { quote: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { quote: "Fall in love with taking care of your body.", author: "Unknown" },
  { quote: "When you feel like quitting, think about why you started.", author: "Unknown" },
  { quote: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy" },
  { quote: "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.", author: "John F. Kennedy" },
  { quote: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
  { quote: "You don't find willpower. You create it.", author: "Unknown" },
  { quote: "Your fitness is 100% mental. Your body won't go where your mind doesn't push it.", author: "Unknown" },
  { quote: "Be the change you want to see in the mirror.", author: "Unknown" },
  { quote: "Go the extra mile. It's never crowded there.", author: "Wayne Dyer" },
  { quote: "Suffer the pain of discipline, or suffer the pain of regret.", author: "Jim Rohn" },
  { quote: "The secret to getting ahead is getting started.", author: "Mark Twain" },
  { quote: "Set your goals high, and don't stop till you get there.", author: "Bo Jackson" },
  { quote: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { quote: "If you want something you've never had, you must do something you've never done.", author: "Unknown" },
  { quote: "It's not about having time. It's about making time.", author: "Unknown" },
  { quote: "The comeback is always stronger than the setback.", author: "Unknown" },
  { quote: "Fitness is a journey, not a destination.", author: "Unknown" },
  { quote: "Run when you can, walk if you have to, crawl if you must — just never give up.", author: "Dean Karnazes" },
  { quote: "You are one workout away from a better mood, a clearer mind, and a stronger version of yourself.", author: "Unknown" },
  { quote: "Don't be afraid of being a beginner.", author: "Unknown" },
  { quote: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma" },
  { quote: "The best project you'll ever work on is yourself.", author: "Unknown" },
]

/**
 * Returns a deterministic quote for today (same quote all day, changes daily).
 */
export function getDailyInspiration() {
  const start = new Date(new Date().getFullYear(), 0, 0)
  const dayOfYear = Math.floor((Date.now() - start) / 86_400_000)
  return QUOTES[dayOfYear % QUOTES.length]
}
